/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void portList_click1(GDropList source, GEvent event) { //_CODE_:portList:368268:
  println("dropList2 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:portList:368268:

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:464036:
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:button1:464036:

public void r1_event(GCustomSlider source, GEvent event) { //_CODE_:r1:912693:
  println(source.getValueI());
  r1_label.setText(str(source.getValueI()));
  R1 = source.getValueI(); 
  byte rgb[]= {byte(R1), byte(G1), byte(B1)}; 
  myPort.write(rgb);
} //_CODE_:r1:912693:

public void LED_list_1_click1(GDropList source, GEvent event) { //_CODE_:LED_list_1:739397:
  println("dropList3 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:LED_list_1:739397:

public void LED_list_2_click2(GDropList source, GEvent event) { //_CODE_:LED_list_2:622348:
  println("dropList3 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:LED_list_2:622348:

public void LED_list_3_click1(GDropList source, GEvent event) { //_CODE_:LED_list_3:571203:
  println("dropList4 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:LED_list_3:571203:

public void LED_list_4_click1(GDropList source, GEvent event) { //_CODE_:LED_list_4:702246:
  println("dropList5 - GDropList >> GEvent." + event + " @ " + millis());
} //_CODE_:LED_list_4:702246:

public void g1_event(GCustomSlider source, GEvent event) { //_CODE_:g1:369718:
  g1_label.setText(str(source.getValueI()));
  G1 = source.getValueI(); 
  byte temp[]= {byte(R1), byte(G1), byte(B1)}; 
  myPort.write(temp);
} //_CODE_:g1:369718:

public void b1_event(GCustomSlider source, GEvent event) { //_CODE_:b1:491279:
  b1_label.setText(str(source.getValueI()));
  B1 = source.getValueI(); 
  byte temp[]= {byte(R1), byte(G1), byte(B1)}; 
  myPort.write(temp);
} //_CODE_:b1:491279:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("LED Controller");
  portList = new GDropList(this, 16, 32, 110, 220, 10, 10);
  portList.setItems(loadStrings("ports.txt"), 0);
  portList.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  portList.addEventHandler(this, "portList_click1");
  label1 = new GLabel(this, 32, 4, 72, 24);
  label1.setText("Serial Port Select");
  label1.setLocalColorScheme(GCScheme.SCHEME_9);
  label1.setOpaque(false);
  button1 = new GButton(this, 16, 56, 112, 30);
  button1.setText("Save Port");
  button1.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  button1.addEventHandler(this, "button1_click1");
  r1 = new GCustomSlider(this, 8, 100, 300, 40, "grey_blue");
  r1.setLimits(255, 0, 255);
  r1.setNumberFormat(G4P.INTEGER, 0);
  r1.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  r1.setOpaque(false);
  r1.addEventHandler(this, "r1_event");
  label2 = new GLabel(this, 340, 108, 40, 20);
  label2.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label2.setText("R");
  label2.setLocalColorScheme(GCScheme.RED_SCHEME);
  label2.setOpaque(true);
  LED_list_1 = new GDropList(this, 144, 32, 66, 198, 10, 10);
  LED_list_1.setItems(loadStrings("list_739397"), 0);
  LED_list_1.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  LED_list_1.addEventHandler(this, "LED_list_1_click1");
  label3 = new GLabel(this, 136, 4, 80, 24);
  label3.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label3.setText(" LEDs On Strip 1");
  label3.setLocalColorScheme(GCScheme.SCHEME_8);
  label3.setOpaque(false);
  LED_list_2 = new GDropList(this, 228, 32, 66, 220, 10, 10);
  LED_list_2.setItems(loadStrings("list_622348"), 0);
  LED_list_2.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  LED_list_2.addEventHandler(this, "LED_list_2_click2");
  LED_list_3 = new GDropList(this, 312, 32, 66, 220, 10, 10);
  LED_list_3.setItems(loadStrings("list_571203"), 0);
  LED_list_3.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  LED_list_3.addEventHandler(this, "LED_list_3_click1");
  LED_list_4 = new GDropList(this, 396, 32, 66, 220, 10, 10);
  LED_list_4.setItems(loadStrings("list_702246"), 0);
  LED_list_4.setLocalColorScheme(GCScheme.CYAN_SCHEME);
  LED_list_4.addEventHandler(this, "LED_list_4_click1");
  label4 = new GLabel(this, 220, 4, 80, 24);
  label4.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label4.setText(" LEDs On Strip 2");
  label4.setLocalColorScheme(GCScheme.SCHEME_8);
  label4.setOpaque(false);
  label5 = new GLabel(this, 304, 4, 80, 24);
  label5.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label5.setText(" LEDs On Strip 3");
  label5.setLocalColorScheme(GCScheme.SCHEME_8);
  label5.setOpaque(false);
  label6 = new GLabel(this, 388, 4, 80, 24);
  label6.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label6.setText(" LEDs On Strip 4");
  label6.setLocalColorScheme(GCScheme.SCHEME_8);
  label6.setOpaque(false);
  g1 = new GCustomSlider(this, 8, 124, 300, 40, "grey_blue");
  g1.setLimits(255, 0, 255);
  g1.setNumberFormat(G4P.INTEGER, 0);
  g1.setOpaque(false);
  g1.addEventHandler(this, "g1_event");
  b1 = new GCustomSlider(this, 8, 148, 300, 40, "grey_blue");
  b1.setLimits(255, 0, 255);
  b1.setNumberFormat(G4P.INTEGER, 0);
  b1.setOpaque(false);
  b1.addEventHandler(this, "b1_event");
  r1_label = new GLabel(this, 308, 108, 32, 20);
  r1_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  r1_label.setText("255");
  r1_label.setLocalColorScheme(GCScheme.SCHEME_8);
  r1_label.setOpaque(false);
  g1_label = new GLabel(this, 308, 132, 32, 20);
  g1_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  g1_label.setText("255");
  g1_label.setLocalColorScheme(GCScheme.SCHEME_8);
  g1_label.setOpaque(false);
  label9 = new GLabel(this, 340, 132, 40, 20);
  label9.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label9.setText("G");
  label9.setLocalColorScheme(GCScheme.GREEN_SCHEME);
  label9.setOpaque(true);
  b1_label = new GLabel(this, 308, 156, 32, 20);
  b1_label.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  b1_label.setText("255");
  b1_label.setLocalColorScheme(GCScheme.SCHEME_8);
  b1_label.setOpaque(false);
  label7 = new GLabel(this, 340, 156, 40, 20);
  label7.setTextAlign(GAlign.CENTER, GAlign.MIDDLE);
  label7.setText("B");
  label7.setOpaque(true);
}

// Variable declarations 
// autogenerated do not edit
GDropList portList; 
GLabel label1; 
GButton button1; 
GCustomSlider r1; 
GLabel label2; 
GDropList LED_list_1; 
GLabel label3; 
GDropList LED_list_2; 
GDropList LED_list_3; 
GDropList LED_list_4; 
GLabel label4; 
GLabel label5; 
GLabel label6; 
GCustomSlider g1; 
GCustomSlider b1; 
GLabel r1_label; 
GLabel g1_label; 
GLabel label9; 
GLabel b1_label; 
GLabel label7; 
